config/routes.rb
Reportwheel::Application.routes.draw do
  


  # get "tests/index"
  scope "(:locale)", locale: /en|kh/ do

    get "test/index"

    # get "ods/index"

    get "contacts/index" 
    get "places/search_place_name"
    post "contacts/create_contact"
    post "places/create_place"
    get "places/update_place"
    get "places/get_parent_level"
    get "places/get_sibling_level"

    delete "places/delete_place"
    delete "contacts/delete_contact"
    # post "users/update_phone"


    # get "reports/render_date"
    # get "reports/render_date_next_previous"
    get "reports/create_hc_chart"
    get "reports/hc_chart"
    get "reports/disease_chart"
    get "reports/create_disease_chart"
    
    resources :places do
      resources :contacts
      get 'get_children', on: :member
      
      # get 'search_place_name', on: :member
    end   

    resources :reports do
      collection do
        get :export_csv
      end
    end

    resources :users do
      get :view
      put :update_current_user
      collection do
        get :reset_password
        put :change_password          
      end
    end

  end






  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  root :to => "reports#index"

  resource :sessions
  
end

app/models/old/user.rb
module Old
	class User < Keansvay
		belongs_to :place
		has_many :reports

		attr_accessible :name, :password, :place_id, :can_login, :phone_number

		validates :place_id, :presence => true
		validates :name, :presence => true
		validates :name, :uniqueness => true


		def provincial?
			self.place && self.place.place_type.code == "PHD"
		end

		def od?
			self.place && self.place.place_type.code == "OD"
		end

		def hc?
			self.place && self.place.place_type.code == "HC"
		end
	
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  
  ADMIN_USER =  1
  DEFAULT_USER = 2
  belongs_to :place
  # has_many :reports, dependent: :destroy
  
  # attr_accessor :old_password, :password_confirmation
  has_secure_password
  attr_accessible :name, :password, :place_id, :can_login, :phone_number, :old_password, :password_confirmation, :level,
                  :created_at, :updated_at

  validates :name, :presence => true
  validates :name, :uniqueness => true   
  validates :place_id, :presence => true, :if => lambda { |user| user.level != ADMIN_USER}
  # validates :phone_number, :presence => true, :if => lambda { |user| user.level != ADMIN_USER}
  validates :password_confirmation, :presence =>true ,:on => :change_password
  # validates :phone_number, format: { with: /^(\+\d{1,3}\s)?\(?\d{2,3}\)?([\s.-]?\d+)*$/, message: :bad_format }, :if => lambda { |user| user.level != ADMIN_USER}

  
  def self.authenticate(name, password)
    user = User.find_by_name(name)

    if !user.nil? && user.can_login
      if user && user.authenticate(password)
        user
      else
        false
      end 
    # else
    #    self.errors.add(:can_login, "No authenticate" )
    #    return false
    end   
  end

  # def validate!
  #   errors.add(:can_login, "cannot be nil") if can_login == false
  # end

  def self.can_login?
    where(:can_login => true)
  end

  def is_member user
    if self.level == 1
      self.members.exists?(user.id)
    else
      self.members.include?(user)
    end
  end

  def members
    if self.level == 1
      @users = User.where('level not in (?)', [1]).order(:name)     
    else
      @users = User.where(:place_id => self.place.children.select(:id))
      if self.place.type == 'Phd'        
        @users.each do |u|
           @users = @users + User.where(:place_id => u.place.children.select(:id))
        end 
      end
      @users.sort_by { |user| user[:name] }
    end
  end

  # def member
  #   User.where(:place_id => self.place.children.select(:id)).order(:name)
  # end

  def provincial?
    self.place && self.place.type == "Phd"
  end

  def od?
    self.place && self.place.type == "Od"
  end

  def hc?
    self.place && self.place.type == "Hc"
  end

  def change_password(params)
    if(self.authenticate(params[:old_password]))
      if params[:password] != ""
        self.password = params[:password]
        self.password_confirmation = params[:password_confirmation]
        return self.save
      else
        self.errors.add(:password, I18n.t('activerecord.errors.models.user.attributes.password.blank'))
        return false
      end
    else
      self.errors.add(:old_password, I18n.t('activerecord.errors.models.user.attributes.old_password.not_match'))
      return false
    end    
  end

  def self.find_by_phone_number_of_reporting_wheel phone_number_rw
    sender_phone_number = phone_number_rw.gsub(/(sms:\/\/)/, "") if phone_number_rw
    User.find_by_phone_number sender_phone_number
  end

  def self.find_by_health_center_contact phone_number_rw
    sender_phone_number = phone_number_rw.gsub(/(sms:\/\/)/, "") if phone_number_rw
    sender_place_id = Contact.find_by_telephone_number(sender_phone_number).place_id
    sender = User.find_by_place_id(sender_place_id)
  end

  def self.find_by_name_ignore_case name
    User.find(:first, :conditions => ["lower(name) = ?", name.downcase])
  end


  def self.construct_place places, result_opts, space
    
    result_opts = result_opts || []
    if places.class != Array
      places = [places]
    end
    count_space = space * 5 
    space = space + 1
    places.each do |place|
      n_space = ""
      nbsp = "&nbsp;"
      n_space = nbsp* count_space      
      result_opts << [n_space + place.name,place.id]      
      construct_place(place.children.to_a, result_opts, space)
    end    
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # helper_method :options_for_place

    
  def index
    if params[:name].present?
      @users = User.where("lower(name) like ?", "%#{params[:name].downcase}%")
    else
      @users = current_user.members      
    end

    if !@users.nil?
      @per_page = 10
      @page = params[:page] || 1
      @users = @users.paginate(:page => params[:page], :per_page => @per_page)
    end
    
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new params[:user]
    if @user.save
      # flash['success'] = "User is created successfully"
      redirect_to users_url, notice: t('user.message.create_success')
    else
      render action: "new"
    end
  end

  def edit
    @user_param = User.find(params[:id])
    if current_user.is_member(@user_param)
      @user = @user_param
    else
      redirect_to users_url, alert: t('user.message.no_edit_authorize')
    end
    
    # @parent_user = User.find(@user.parent_id)
  end

  def update
    @user_param = User.find(params[:id])
    if current_user.is_member(@user_param) 
      @user = @user_param      
      if @user.update_attributes(params[:user])
        redirect_to users_url, notice: t('user.message.update_success')
      else
        render action: "edit"
      end
    else
      redirect_to users_url, alert: t('user.message.no_edit_authorize')
    end
  end

  def destroy
    @user = User.find(params[:id])
    if current_user.is_member(@user)
      @user.destroy      
      redirect_to users_url, notice: t('user.message.delete_success')      
    else
      redirect_to users_url, alert: t('user.message.no_edit_authorize')
    end
    
  end

  def reset_password
    @user = current_user
  end

  def change_password
    @user = current_user
    if @user.change_password(params[:user])
      # flash["success"] = "Updated successfully"
      redirect_to reports_url, notice: t('user.message.password_updated')
    else
      render action: "reset_password"
    end
  end

  # def update_phone
  #   @user = User.where(:phone_number => params[:phone_number])
  #   response = @user.update_all(:phone_number => nil)
  #   if response
  #     render json: response
  #   else
  #     render json: nil
  #   end
  # end

  def update_current_user
    @user = User.find(current_user.id)
    if @user.update_attributes(params[:user])
      redirect_to users_url, notice: t('user.message.update_success')
    else
      render action: "view"
    end
  end
  # def update_current_user
  #   @user_param = User.find(params[:user_id])
  #   if current_user.is_member(@user_param) 
  #     @user = @user_param      
  #     if @user.update_attributes(params[:user])
  #       redirect_to users_url, notice: 'User was successfully updated.'
  #     else
  #       render action: "view"
  #     end
  #   else
  #     redirect_to users_url, alert: 'You are not authorize to edit this user.'
  #   end
  # end

  def view
    @user = User.find(params[:user_id])
    # @parent_user = User.find(@user.parent_id)
  end

  # def options_for_place
  #   if current_user.name == 'admin'
  #     user_places = Phd.all.to_a
  #   else
  #     user_places = current_user.place.children.to_a
  #   end
  #   result_opt = []
  #   User.construct_place user_places, result_opt, 0
  #   result_opt
  # end

end

app/views/users/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <%= t('action.new_user')  %>
  </div>
  <div class="panel-body">
    <%= form_for(@user, :html => { :class => 'form-horizontal ' }) do |f| %>
      <% if @user.errors.any? %>
          <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <!-- <p><%#= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</p> -->

            <ul>
              <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        
        <% end %>

      <div class="control-group">
        <label><%= t('user.username') %></label>
        <%#= f.label t('user.username') %>
        <div class="controls">      
          <%= f.text_field :name %><span class="text-error">*</span>
        </div>
      </div>

      <div class="control-group">
        <label><%= t('user.password') %></label>
        <div class="controls">
          <%= f.password_field :password %><span class="text-error">*</span>
        </div>
      </div>

       <!--  <div class="control-group">
          <%= f.label "Password confirmation" %>
          <div class="controls">
            <%= f.password_field :password_confirmation %><span class="text-error">*</span>
          </div>
        </div>   -->

      <div class="control-group">
        <label><%= t('user.phone') %></label>
        <div class="controls">
          <%= f.telephone_field :phone_number %><span class="text-error">*</span>
        </div>
      </div>

      <div class="control-group">
        <label><%= t('user.place') %></label>
        <div class="controls">     

          <%= select_place @user, "user[place_id]", "user_place_id" %>
          <%#= f.select(:place_id, options_for_place, {include_blank: 'Select Place'}, :class => 'input-xlarge') %>


          <span class="text-error">*</span>
        </div>
      </div>

      <div class="control-group">
        <label><%= t('user.can_login') %></label>
        <div class="controls">
          <%#= f.select(:can_login, [["#{t('user.can')}", true], ["#{t('user.cannot')}", false]]) %>
          <%= t('user.can') %>&nbsp;<%= f.radio_button(:can_login, true) %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <%= t('user.cannot') %>&nbsp;<%= f.radio_button(:can_login, false)%>
        </div>
      </div>

      <div class="control-group">
         <div class="controls">
            <%= f.submit t('action.create'), :class => 'btn btn-primary' %>
         </div>
      </div>
    <% end %>

  </div>
</div>

app/views/users/edit.html.erb
<%=  link_to t('action.back'), users_path %>
<br /><br />

<div class="panel panel-default">
  <div class="panel-heading">
    <%= t('action.edit')  %> <%= t('user.user')%>   
  </div>
  <div class="panel-body">
    <%= form_for(@user, :html => { :class => 'form-horizontal ' }) do |f| %>
      <% if @user.errors.any? %>
          <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <!-- <p><%#= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</p> -->

            <ul>
              <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
 
        <% end %>

      <div class="control-group">
        <label><%= t('user.username') %></label>
        <div class="controls">      
          <%= f.text_field :name%><span class="text-error">*</span>
        </div>
      </div>

 

      <div class="control-group">
        <label><%= t('user.phone') %></label>
        <div class="controls">
          <%= f.telephone_field :phone_number %><span class="text-error">*</span>
        </div>
      </div>

      <div class="control-group">
        <label><%= t('user.place') %></label>
        <div class="controls">           
          <%= select_place @user, "user[place_id]", "user_place_id" %>
          <%#= select("user","place_id", @select.collect {|p| [ p['label'], p['value'] ] }, {include_blank: 'Select Place'}, :class => 'input-xlarge') %>
          <span class="text-error">*</span>
        </div>
      </div>

      <div class="control-group">
        <label><%= t('user.can_login') %></label>
        <div class="controls">
          <%= t('user.can') %>&nbsp;<%= f.radio_button(:can_login, true) %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <%= t('user.cannot') %>&nbsp;<%= f.radio_button(:can_login, false)%>
        </div>
      </div>

      <div class="control-group">
         <div class="controls">
            <%= f.submit t('action.update'), :class => 'btn btn-primary' %>
         </div>
      </div>
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<% if params[:name].present? %>
  <%=  link_to t('action.back'), users_path %>
<% end %>
<br>
<br>
  <div class="panel panel-default">
    <div class="panel-heading">
      <%= t('action.list_all_user')%> 
    </div>
    <div class="panel-body">
        
        <%#= flash["success"] %>
        <% if @users.any? %>
          <%= form_tag "/users", method: "get" do %>
            <div class="btn-group">
              <%= text_field_tag :name, nil, placeholder: "#{t('action.search')}" %>
              <%= submit_tag "Search", :class => 'btn hidden' %>
            </div>
          <% end %>
          <table class="table table-hover">
            <thead>
              <tr>
                <th>#</th>
                <th><%= t('user.username')%></th>
                <th><%= t('user.phone')%></th>
                <th><%= t('user.location')%></th>
               <!--  <th>Type</th> -->
                <th><%= t('user.can_login')%></th>
                <th></th>
              </tr>
            </thead>

            <% @users.each_with_index do |user, i| %>
              <tr>
                <td><%= (@page.to_i*@per_page)-@per_page+i+1%></td>
                <td title="<%= user.name %>"><%= user.name %></td>
                <td title="<%= user.phone_number %>"><%= user.phone_number %></td>
                <td title="<%= user.place.name if !user.place.nil? %>"><%= user.place.name  if !user.place.nil? %></td>
                <td title="<%= user.can_login %>"><%= user.can_login %></td>
                <td>
                  
                  <%#= link_to t('action.edit'), edit_user_path(user) %> 
                  <%#= link_to t('action.delete'), user, method: :delete, data: { confirm: t('message.delete') } %>

                  <%= link_to(edit_user_path(user), :class => 'btn btn-small', :title => t('action.edit')) do %>
                    <i class="icon-pencil"></i>
                  <% end %>
                  <%= link_to user, method: :delete,  data: { confirm: t('message.delete') }, :class => 'btn btn-small', :title => t('action.delete') do %>
                      <i class="icon-remove"></i>
                  <% end %>
                  
                </td>
              </tr>
            <% end %>
          </table>

        <% else %>         
          <p class="text-error">
            No any users found.
          </p>
        <% end %>
      <div class="span2"><%= link_to t('action.new_user'), new_user_url, :class => 'btn' %></div>  
      <div class="pagination pull-right">
          <%= will_paginate @users, renderer: BootstrapPagination::Rails %>
      </div>
      <br>
      <br><br>
      <br>
    </div>
  </div>

app/views/users/new.html.erb
<%=  link_to t('action.back'), users_path %>
<br /><br />
<%= render 'users/form' %> 

app/views/users/reset_password.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <%= t('menu.change_password')%>
  </div>
  <div class="panel-body">
    <%= form_for(@user,{url: change_password_users_path, :html => { :class => 'form-horizontal' }}) do |f| %>
      <!-- <fieldset> -->
        <!-- <legend>Change Password</legend> -->
        <% if @user.errors.any? %>
        <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <!-- <p><%#= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</p> -->
            <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
        </div>    
      <% end %>

        <div class="control-group" >
          <label><%= t('user.old_password')%></label>
          <div class="controls">
            <%= f.password_field "old_password" %><span class="text-error">*</span>
          </div>
        </div> 

        <div class="control-group">
           <label><%= t('user.new_password')%></label>
          <div class="controls">
            <%= f.password_field :password %><span class="text-error">*</span>
          </div>  
        </div>

        <div class="control-group">
           <label><%= t('user.new_password_confirmation')%></label>
          <div class="controls">
            <%= f.password_field :password_confirmation %><span class="text-error">*</span>
          </div>
        </div>

        <div class="control-group">
          <div class="controls">
            <%#= f.submit "Cancel", :type => "reset", :class => 'btn' %>
            <%= f.submit t('action.save'), :class => 'btn btn-primary' %>
          </div>
        </div>
       <!--  </fieldset> -->

    <% end %>


  </div>
</div>

app/views/users/test.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>jQuery metisMenu Plugin Demos</title>

<style>
  .arrow {
    float: right;
  }
  .glyphicon.arrow:before {
    content: "\e079";
  }
  .active > a > .glyphicon.arrow:before {
    content: "\e114";
  }
  .fa.arrow:before {
    content: "\f104";
  }
  .active > a > .fa.arrow:before {
    content: "\f107";
  }
  .plus-times {
    float: right;
  }
  .fa.plus-times:before {
    content: "\f067";
  }
  .active > a > .fa.plus-times {
     filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=1);
    -webkit-transform: rotate(45deg);
    -moz-transform: rotate(45deg);
    -ms-transform: rotate(45deg);
    -o-transform: rotate(45deg);
    transform: rotate(45deg);
  }
  .plus-minus {
    float: right;
  }
  .fa.plus-minus:before {
    content: "\f067";
  }
  .active > a > .fa.plus-minus:before {
    content: "\f068";
  }
</style>
</head>
<body>

<h1 style="margin-top:150px" align="center">jQuery metisMenu Plugin Demos</h1>
<div class="container">
<div class="row">
<div class="col-lg-3">
<h3>Auto Collapse</h3>
  <ul id="menu">
    <li class="active"> <a href="#">Menu 0 <span class="fa arrow"></span></a>
      <ul>
        <li><a href="#">item 0.1</a></li>
        <li><a href="#">item 0.2</a></li>
        <li><a href="http://onokumus.com">onokumus</a></li>
        <li><a href="#">item 0.4</a></li>
      </ul>
    </li>
    <li> <span class="icon-arrow-right"></span> <a href="#">Menu 1</a>
      <ul>
        <li><a href="#">item 1.1</a></li>
        <li><a href="#">item 1.2</a></li>
        <li> <a href="#">Menu 1.3 <span class="fa plus-times"></span></a>
          <ul>
            <li><a href="#">item 1.3.1</a></li>
            <li><a href="#">item 1.3.2</a></li>
            <li><a href="#">item 1.3.3</a></li>
            <li><a href="#">item 1.3.4</a></li>
          </ul>
        </li>
        <li><a href="#">item 1.4</a></li>
        <li> <a href="#">Menu 1.5 <span class="fa plus-minus"></span></a>
          <ul>
            <li><a href="#">item 1.5.1</a></li>
            <li><a href="#">item 1.5.2</a></li>
            <li><a href="#">item 1.5.3</a></li>
            <li><a href="#">item 1.5.4</a></li>
          </ul>
        </li>
      </ul>
    </li>
    <li> <a href="#">Menu 2 <span class="glyphicon arrow"></span></a>
      <ul>
        <li><a href="#">item 2.1</a></li>
        <li><a href="#">item 2.2</a></li>
        <li><a href="#">item 2.3</a></li>
        <li><a href="#">item 2.4</a></li>
      </ul>
    </li>
  </ul>
</div>

<script>
    $(function () {

        $('#menu').metisMenu();

        $('#menu2').metisMenu({
            toggle: false
        });
    });
</script>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-36251023-1']);
  _gaq.push(['_setDomainName', 'jqueryscript.net']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</body>
</html>

app/views/users/view.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <%= t('action.edit')  %> <%= t('user.user')%>   
  </div>
  <div class="panel-body">
    <%= form_for(@user, :html => { :class => 'form-horizontal '}, :url => { :action => :update_current_user }) do |f| %>
      <% if @user.errors.any? %>
          <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <!-- <p><%#= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</p> -->

            <ul>
              <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
 
        <% end %>

      <div class="control-group">
        <label><%= t('user.username') %></label>
        <div class="controls">      
          <%= f.text_field :name%><span class="text-error">*</span>
        </div>
      </div>

 

      <div class="control-group">
        <label><%= t('user.phone') %></label>
        <div class="controls">
          <%= f.telephone_field :phone_number %><span class="text-error">*</span>
        </div>
      </div>

      <div class="control-group">
         <div class="controls">
            <%= f.submit t('action.update'), :class => 'btn btn-primary' %>
         </div>
      </div>
    <% end %>

  </div>
</div>