config/routes.rb
Reportwheel::Application.routes.draw do
  


  # get "tests/index"
  scope "(:locale)", locale: /en|kh/ do

    get "test/index"

    # get "ods/index"

    get "contacts/index" 
    get "places/search_place_name"
    post "contacts/create_contact"
    post "places/create_place"
    get "places/update_place"
    get "places/get_parent_level"
    get "places/get_sibling_level"

    delete "places/delete_place"
    delete "contacts/delete_contact"
    # post "users/update_phone"


    # get "reports/render_date"
    # get "reports/render_date_next_previous"
    get "reports/create_hc_chart"
    get "reports/hc_chart"
    get "reports/disease_chart"
    get "reports/create_disease_chart"
    
    resources :places do
      resources :contacts
      get 'get_children', on: :member
      
      # get 'search_place_name', on: :member
    end   

    resources :reports do
      collection do
        get :export_csv
      end
    end

    resources :users do
      get :view
      put :update_current_user
      collection do
        get :reset_password
        put :change_password          
      end
    end

  end






  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  root :to => "reports#index"

  resource :sessions
  
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	belongs_to :place

  	attr_accessible :place_id, :telephone_number, :created_at, :updated_at
  	
  	validates :telephone_number, :presence => true
  	validates :telephone_number, :uniqueness => true
	validates :telephone_number, format: { with: /^(\+\d{1,3}\s)?\(?\d{2,3}\)?([\s.-]?\d+)*$/, message: :bad_format }
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @place = Place.find(params[:place_id])
    @contacts = @place.contacts

    respond_to do |format|
      format.json  { render :json => @contacts }      
    end
  end

  def new
    @place = Place.find(params[:place_id])
  	@contact = @place.contacts.build
  end

  def create_contact
    contact = Contact.new telephone_number: params[:telephone_number].strip, place_id: params[:place_id]
    # response = {success: contact.save}
    if contact.save == true
     render json: contact
    else
      p contact.errors.full_messages
      render json: contact.errors.full_messages
    end
     
  end

  def create    
    
    @place = Place.find(params[:place_id])  
    @contact = @place.contacts.build(:telephone_number => params[:telephone_number].strip)
    result = @contact.save
   
    if result
      flash['success'] = "successfully"
      redirect_to place_contacts_path(@place)
    else
      flash.now[:error] = "Error"
      render action: "new"
    end
 

    
  end

  def destroy
    @place = Place.find(params[:place_id])
    # @contact = Contact.where(:telephone_number => params[:telephone_number], :place_id => params[:place_id])
    @contact = Contact.find(params[:id])
    @contact.destroy

    redirect_to place_contacts_url(@place.id), notice: 'Contact was successfully deleted.'    
  end

  def delete_contact
    contact = Contact.find(params[:id])
    place = Place.find(contact.place_id)
    access_key = enable_access_level(place)
    if access_key
      if !params[:parent_id].present?
        parent_id = nil
      else
        parent_id = params[:parent_id]
      end
      @current_place_id = params[:id]
      response = contact.destroy
    else
      response = place.errors.add("Unknow", "Error");
    end
    
    render json: response    
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/contacts/_form.html.erb
<%= form_for([@place, @contact], :html => { :class => 'form-horizontal col-xs-6' }) do |f| %>
	<fieldset>
		<legend>Add new phone number</legend>

		<% if @contact.errors.any? %>
	    <div class="text-danger">
	      <p><%= pluralize(@contact.errors.count, "error") %> prohibited this user from being saved:</p>

	      <ul>
	      <% @contact.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	    <% end -%>

		<div class="form-group">
		    <%= f.label :telephone_number , :class => 'text-right col-sm-4 control-label' %>
		    <div class="col-sm-8">
		    	<%= f.text_field :telephone_number, :class => 'form-control' %>
		    </div>			
		</div>

		
		<div class="form-group">
		    <div class="col-sm-offset-9 col-sm-3">
		    	<%= f.submit "Create", :class => 'btn btn-default' %>
		    </div>
		</div>		
	</fieldset>
<% end %>

app/views/contacts/index.html.erb
<div class="row">
	
	<div class="page-header">
		<h2><%= @place.name %></h2>
		<p>The report comes from any of the phones below</p>
		<%= link_to 'Add new phone number', new_place_contact_path(@place) %>
	</div>

</div>

<div class="row">
	<ul>
		<% @place.contacts.each do |c| %>
		<li>
			<%= c.telephone_number %>
			<%= link_to '-', place_contact_path(@place,c),
            :confirm => 'Are you sure, you want to delete?',
            :method => :delete,
            :class => 'btn btn-default' %>
		</li>
		<% end -%>
	</ul>
	<%= link_to 'Delete this HC', place_path(@place),
            :confirm => 'Are you sure, you want to delete?',
            :method => :delete,
            :class => 'btn btn-default' %>
</div>

app/views/contacts/new.html.erb
<%= render 'contacts/form' %> <br />
<%#= debug("foo\n\nbar".indent(2))%>