config/routes.rb
Reportwheel::Application.routes.draw do
  


  # get "tests/index"
  scope "(:locale)", locale: /en|kh/ do

    get "test/index"

    # get "ods/index"

    get "contacts/index" 
    get "places/search_place_name"
    post "contacts/create_contact"
    post "places/create_place"
    get "places/update_place"
    get "places/get_parent_level"
    get "places/get_sibling_level"

    delete "places/delete_place"
    delete "contacts/delete_contact"
    # post "users/update_phone"


    # get "reports/render_date"
    # get "reports/render_date_next_previous"
    get "reports/create_hc_chart"
    get "reports/hc_chart"
    get "reports/disease_chart"
    get "reports/create_disease_chart"
    
    resources :places do
      resources :contacts
      get 'get_children', on: :member
      
      # get 'search_place_name', on: :member
    end   

    resources :reports do
      collection do
        get :export_csv
      end
    end

    resources :users do
      get :view
      put :update_current_user
      collection do
        get :reset_password
        put :change_password          
      end
    end

  end






  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  root :to => "reports#index"

  resource :sessions
  
end

app/models/old/report.rb
module Old
	class Report < Keansvay
	  attr_accessible :created_at, :disease, :from, :lat, :lon, :quantity, :sender, :to, :user_id, :place_id
	  belongs_to :user
	  belongs_to :place
	end
end

app/models/report.rb
class Report < ActiveRecord::Base
  attr_accessible :created_at, :disease, :from, :lat, :lon, :quantity, :sender, :to, :user_id, :place_id
  belongs_to :user
  belongs_to :place

  REPORT_TYPE = {:weekly => "Weekly", :monthly => "Monthly", :yearly => "Yearly"}
  
  def self.between from_date, to_date
    where(:created_at => from_date..to_date+1)
  end

  public 
  def self.child_place_of place
    joins(:place).where("places.parent_id" => place.id)
  end

  def self.from_disease disease
    where(:disease => disease)
  end

  def self.find_by_place place_id
    where(:place_id => place_id)
  end

  def self.find_by_place_disease_and_date(place_id, disease, from_date, to_date)
    # records = Report.from_disease(disease).find_by_place(user)
    records = Report.from_disease(disease).between(from_date,to_date).where(:place_id => place_id)
    if records.count > 0
      records[0]
    else
      nil
    end
  end

  def self.find_no_disease report_cases
    report_cases.select{|disease, quantity| disease == "No_Disease"}.count
  end

  def self.handle_update_and_create report_place_id, report_cases, options
    date = Time.now.to_date
    date_range = date.to_range("Weekly")
    from_date = date_range.from_date
    to_date = date_range.to_date
    no_disease = Report.find_no_disease report_cases

    # user = User.find_by_name_ignore_case options[:sender]

    if no_disease > 0
      report = Report.update_all("quantity = 0", :created_at => from_date...to_date, :place_id => report_place_id)
    end

    report_cases.each do |disease, quantity|
      record = Report.find_by_place_disease_and_date(report_place_id, disease, from_date, to_date)
     
      if !record.nil?
        record.quantity = (no_disease > 0) ? 0 : quantity
        record.save        
      else
        Report.create(:sender => options[:sender],
          :disease => disease, :quantity => quantity, :from => options[:from],
          :lat => options[:lat], :lon => options[:lon], :to => options[:to], :place_id => report_place_id)
      end
    end   
  end
  
  def self.total_cases_by_disease_place_date user, from_date, to_date
    if user.level == 2
      place_id = user.place_id
      p_type = Place.find(place_id).type
    end

    if p_type == "Od"
      results = joins(:place).where("places.parent_id" => place_id).between(from_date, to_date+1.days).group("places.id", "reports.disease").sum(:quantity)
    elsif p_type == "Phd"
      p_ods = Place.where("parent_id" => place_id)
      results = Hash.new
      p_ods.each do |p_od|
        tmp = joins(:place).where("places.parent_id" => p_od.id).between(from_date, to_date+1.days).group( "places.parent_id","reports.disease").sum(:quantity)
        tmp.each do |key,value|
          results[key] = value
        end
      end
    else
      p_phds = Phd.all
      results = Hash.new
      p_phds.each do |p_phd|
        p_ods = p_phd.children
        arr = []
        p_ods.each do |p_od|
          arr << p_od.id
        end
        tmp = joins(:place).where("places.parent_id" => arr).between(from_date, to_date+1.days).group("reports.disease").sum(:quantity)
        tmp.each do |key,value|
          arr_key = [p_phd.id.to_s]
          arr_key << key
          results[arr_key] = value
        end     
      end
    end
    results
  end


  def self.total_cases_by_disease_place place_id
    p_type = Place.find(place_id).type
    if p_type == "Od"
      results = joins(:place).where("places.parent_id" => place_id).group("places.id", "reports.disease").sum(:quantity)
    else
      p_ods = Place.where("parent_id" => place_id)
      results = Hash.new
      p_ods.each do |p_od|    
        tmp = joins(:place).where("places.parent_id" => p_od.id).group( "places.parent_id","reports.disease").sum(:quantity)
        tmp.each do |key,value|
          results[key] = value
        end
      end
    end
    results
  end
  




  def self.search_disease_in_report reports, disease, place_id
    reports.each do |key,value|
        if key[0].to_s == place_id.to_s && key[1] == disease
          return value
        end
    end    
    return 0
  end


  def self.search_by_place_date places_id, from_date, to_date, current_place_type
    if current_place_type.nil?
      results = Hash.new
      places = places_id
      places.each do |place|
        ods = Place.find(place).children
        arr_place = []
        ods.each do |od|
          arr_place << od.id
        end
        tmp = joins(:place).where("places.parent_id" => arr_place).between(from_date, to_date+1.days).select("reports.created_at").group('reports.disease').sum(:quantity)
        
        tmp.each do |key,value|
          if results.has_key? key
            results[key] = results[key] + value
          else
            results[key] = value
             
          end
        end
      end
    elsif current_place_type  == 'Od'
      results = joins(:place).where("places.id" => places_id).between(from_date, to_date+1.days).select("reports.created_at").group('reports.disease').sum(:quantity)
    else
      results = joins(:place).where("places.parent_id" => places_id).between(from_date, to_date+1.days).select("reports.created_at").group('reports.disease').sum(:quantity)
    end    
    results
  end

  def self.chart_by_place_date places_id, from_date, to_date, current_place_type
    if current_place_type  == 'Od'
      results = joins(:place).where("places.id" => places_id).between(from_date, to_date+1.days).select("reports.created_at, reports.disease, sum(quantity) quantity").group("reports.created_at","reports.disease").order('created_at')
    else
      results = joins(:place).where("places.parent_id" => places_id).between(from_date, to_date).select("reports.created_at, reports.disease, sum(quantity) quantity").group("reports.created_at","reports.disease").order('created_at')
    end    
    results
  end

  def self.chart_by_place_date_disease  places_id, from_date, to_date, diseases
    results = joins(:place).where("places.id" => places_id, "reports.disease" => diseases).between(from_date, to_date+1.days).select("reports.created_at, places.name, sum(quantity) quantity").group("reports.created_at","places.name").order('created_at')
  end

  def self.create_data_source data
    arr = []
    data.each do |key,value|
      tmp = [key]
      tmp << value
      arr << tmp
      tmp = []
    end
    arr
  end

  def self.validate_date_range from_date, to_date
    if from_date < to_date
      return true
    end
    return false
  end

end

app/controllers/reports_controller.rb
require "csv"
require 'date'
class ReportsController < ApplicationController

  skip_before_filter :check_authentication, :only => [:create] 

  def index

    date = (params[:from].present?) ? Date.strptime(params[:from], "%Y-%m-%d") : Time.new.to_date    
    @previous_view = params[:report_by]
    @report_by = params[:report_by].present? ? params[:report_by] : "Weekly"

    date_range = date.to_range(@report_by)
    @week_number = date_range.number if date_range.kind_of? Week
    @from_date = date_range.from_date  
    @to_date = date_range.to_date

    if(current_user.level == 1)
      sub_places = Phd.all
      @place_type = nil
    else
      sub_places = current_user.place.children.all
      @place_type = current_user.place.type
    end

    if params[:places].present?
      @places = params[:places]
    else
      @places = []
      sub_places.each do |p|
        @places << p.id
      end
    end

    @time_range = @from_date.to_s+" - "+@to_date.to_s
    @diseases = Disease.by_name.sort
    @diseases.delete('No')

    @reports = Report.total_cases_by_disease_place_date current_user, @from_date, @to_date
    @rows  = create_table @reports, @diseases, sub_places, @places

    @places.delete(0) 
    @places.delete("0") 
    

    results = Report.search_by_place_date @places, @from_date, @to_date, @place_type    
    @places_name = Place.get_places_name @places
   
    if !results.nil? 
      @data_source = Report.create_data_source results 
    end
    
    if request.xhr?
       render 'index_ajax', layout:false
    end

  end



  def create
    p request.raw_post
    report_cases = RWCaseParser.parse request.raw_post
    p report_cases

    user = User.find_by_health_center_contact params[:from] if params[:from]
    # user = User.find_by_phone_number_of_reporting_wheel params[:from] if params[:from]

    if !user.nil? and user.hc?
      Report.handle_update_and_create user.place_id, report_cases, params
    else
      raise Exception.new("User does not exist!")
    end
    render layout:false
  end


  def export_csv 
    from_date = Date.strptime(params[:from], "%Y-%m-%d") if params[:from].present?
    to_date = Date.strptime(params[:to], "%Y-%m-%d") if params[:to].present? 
    
    if current_user.level == 1
      places = Phd.all
    else
      places = current_user.place.children.all
    end
    diseases = Disease.by_name.sort
    diseases.delete('No')

    results = Report.total_cases_by_disease_place_date current_user, from_date, to_date
    rows  = create_csv_data_row results, diseases, places

    from_date = from_date.strftime("%d-%m-%Y")
    to_date = to_date.strftime("%d-%m-%Y")

    csv_string = CSV.generate do |csv|
      rows.each do |r|
        csv << r
      end
      csv
    end

    send_data csv_string,
      :type => 'text/csv; charset=iso-8859-1; header=present',
      :disposition => "attachment; filename = #{from_date}_to_#{to_date}_zero_report.csv"
  end

  def create_table_head diseases
    row = []
    if(current_user.level == 1)
      name = t('place.provincial_health_department')
    else
      name =  current_user.place.child_class == Od ? t("place.operational_district") : t("place.health_center")
    end
    row << name
    row + diseases
  end

  def create_csv_data_row reports, diseases, places
    header = create_table_head(diseases)
    
    rows = [header]
    footer_row = []
    header.each do |h|
      footer_row << 0
    end
   
    places.each do |place|      
      row = [place.name]
      diseases.each_with_index do |disease, i|         
        value = Report.search_disease_in_report(reports, disease, place.id) 
        row << value        
        footer_row[i+1] = footer_row[i+1] + value
      end
      rows << row
    end
    
    footer_row[0] = t('report.total')   
    rows << footer_row
  end

  def create_table reports, diseases, places, checked_places
    header = create_table_head(diseases)
    
    rows = [header]
    footer_row = ["",""]
    header.each do |h|
      footer_row << 0
    end
   
    places.each do |place|      
      row = [place.id]
      row << place.name
      diseases.each_with_index do |disease, i|         
        value = Report.search_disease_in_report(reports, disease, place.id) 
        row << value
        if checked_places.include?(place.id) ||  checked_places.include?(place.id.to_s)
          footer_row[i+2] = footer_row[i+2] + value
        end
      end
      rows << row
    end
    
    footer_row[0] = ""
    footer_row[1] = t('report.total') 
    footer_row.delete_at(footer_row.length-1)

    rows << footer_row
  end


  def hc_chart  
    @hcs = Hc.all
    @place_id = params[:place_id]
    @start_date = params[:start_date]
    @end_date = params[:end_date]
  end  

  def create_hc_chart
    @hcs = Hc.all

    place_id = params[:place_id]
    start_date = params[:start_date].to_date
    end_date = params[:end_date].to_date

    if Report.validate_date_range(start_date,end_date)
      results = Report.chart_by_place_date place_id, start_date, end_date, current_user.place.type
    else
      results = nil
    end

    respond_to do |format|
      format.json  { render :json => results }      
      format.html
    end    
  end

  def disease_chart
    @diseases = Disease.by_name.sort
    @diseases.delete('No')
    @places = current_user.place.children.all
  end

  def create_disease_chart
    places = params[:places]
    start_date = params[:start_date].to_date
    end_date = params[:end_date].to_date
    diseases = params[:diseases]

    if Report.validate_date_range(start_date,end_date)
      results = Report.chart_by_place_date_disease places, start_date, end_date, diseases
    else
      results = nil
    end

    respond_to do |format|
      format.json  { render :json => results }      
      format.html
    end   
  end


end

app/helpers/reports_helper.rb
module ReportsHelper
  def link_calendar_to date, report_by, step = 1
    if report_by === "Weekly"
      from_date = date + (step * 7).days
      to_date = from_date + 6.days
    elsif report_by === "Monthly"
      from_date = Date.new(date.year, date.mon, 1) + step.month
      to_date = from_date + 1.month - 1.days
    else
      from_date = Date.new(date.year + step, 1, 1)
      to_date = from_date + 1.year - 1.days
    end

    link_to step == 1? ">" : "<", reports_path(:from => from_date, :to => to_date, :report_by => report_by, :previous_view => @previous_view), :title => from_date
  end

  def crosstab rows, columns, values
    crosstab = Crosstab.generate rows, columns, values

    html_string = "<table class='table table-hover'>"

    # generate table headers
    html_string += "<thead>"
    crosstab[:headers].each do |column|
      html_string += "<th title=#{column}>" + column +"</th>"
    end
    html_string += "</thead>"

    # generate table body
    html_string += "<tbody>"
    td_style = ""
    tr_style = ""
    crosstab[:bodies].each do |values|
      values.compact.length > 1 ? tr_style = "": tr_style = "missedReport"
      html_string += "<tr class=#{tr_style}>"
      values.each do |value|
        if value.kind_of? Integer
          value.eql?(0) ? td_style = "zeroValue": td_style = "nonZeroValue"
        else
          td_style = "disease"
        end
        html_string += "<td title=#{value} class='#{td_style}'>#{value}</td>"
      end
      html_string += "</tr>"
    end

    # generate total reporting cases
    html_string += "<tr class='footer'>"
    crosstab[:footers].each do |value|
      if value.kind_of? Integer
          value.eql?(0) ? td_style = "zeroValue": td_style = "nonZeroValue"
        else
          td_style = "total"
      end
      html_string += "<td class='#{td_style}'>#{value}</td>"
    end
    html_string += "</tr>"

    html_string += "</tbody>"
    html_string += "</table>"
    html_string.html_safe
  end
end

app/views/reports/_chart_view.html.erb
<%= debug(@results) %>

<div id="chart_div"></div>

app/views/reports/_view.html.erb
<%#= form_tag reports_path, :method => :get, :id => :report_form do %>

  <div  class="row-fluid">
    <div class="span3 btn_report">
      <%
          weekly_active = @report_by == "Weekly" ? "active" : ""
          monthly_active = @report_by == "Monthly" ? "active" : ""
          yearly_active = @report_by == "Yearly" ? "active" : ""
       %>
       <div class="btn-group">
          <button id="report_by_weekly" class="btn <%= weekly_active %>"><%= t('report.weekly') %></button>
          <button id="report_by_monthly" class="btn <%= monthly_active %>"><%= t('report.monthly') %></button>
          <button id="report_by_yearly" class="btn <%= yearly_active %>"><%= t('report.yearly') %></button>
       </div>
    </div>
    
    <div class="span2 offset1">
        <div class="btn-group">
          <button class="btn" id="previous_date_btn"><i class="icon-chevron-left"></i></button>
          <button class="btn" id="next_date_btn"><i class="icon-chevron-right"></i></button>
        </div>
    </div>

    <div class="span2 exportCSV pull-right">
      <%= link_to(t('report.export_as_csv'),export_csv_reports_path(:from => @from_date, :to => @to_date), :class => 'btn btn-info') %>     
    </div>
  </div>
<!--   <br>
  <div  class="row-fluid">
    <div class="span1">
      <button class="btn">Today</button>
    </div>
    <div class="span2">
        <div class="btn-group">
          <button class="btn" id="previous_date_btn"><i class="icon-chevron-left"></i></button>
          <button class="btn" id="next_date_btn"><i class="icon-chevron-right"></i></button>
        </div>
    </div>
  </div> -->
    <%= hidden_field_tag(:report_by, @report_by) %>
    <%= hidden_field_tag(:previous_view, @previous_view) %>
    <%= hidden_field_tag(:from, @from_date) %>
    <%= hidden_field_tag(:to, @to_date) %>

    <!-- <div class="span3"> -->
      <%# if @report_by == "Weekly" %>
        <!-- Week: <%#= @week_number %> -->
      <%# end %>
    <br>
    <div  class="row-fluid">
      <div id="start_date" class="span6">
        <% if @from_date.strftime("%Y") == @to_date.strftime("%Y") %>
            <% if @from_date.strftime("%b") == @to_date.strftime("%b") %>
                  <%= @from_date.strftime("%B %d") %> - <%= @to_date.strftime("%d, %Y") %>
            <% else %>
                  <%= @from_date.strftime("%B %d") %> - <%= @to_date.strftime("%B %d, %Y") %>
            <% end %>
        <% else %>
          <%= @from_date.strftime("%d %b, %Y") %> - <%= @to_date.strftime("%d %b, %Y") %>
        <% end %>         
      </div>


    </div>
  


<div class="row-fluid">
<table class="table table-hover" cellspacing="0" cellpadding="0">
  <thead>
    <tr>
      <th></th>
    <% @rows.first.each do |r| %>
      <th><%= r %></th>
    <% end %>
    </tr>
  </thead>
  <tbody>
    
   
    <% n = @rows.size-1 %>
    <%  n.times.each do |i| %>
      <% if i < n-1 %>
        <% b = true %>
      <% end %>
      
        <% row = @rows[i+1] %>         
        <% row.each.with_index do |r,index| %>
          <% if b == true %>            
          <td>
              <label class="checkbox">
                  <% if index == 0 %>
                    <% if @places.include?(r) || @places.include?(r.to_s) %>
                      <input type="checkbox" class="places" name="places" checked value="<%= r %>">
                    <% else %>
                      <input type="checkbox" class="places" name="places" value="<%= r %>">
                    <% end %>
                  <% end -%>
              </label>                
            <% b = false %>              
          </td>
          <% else %>
            
            <td>
              <% if index == 1%>
                <% if i < n-1 %>
                  <% if @place_type == 'Od' %>
                    <%= link_to r, reports_hc_chart_path(:place_id => row[0], :start_date => @from_date, :end_date => @to_date, :locale => params[:locale]) %>
                  <% elsif @place_type == 'Phd' %>
                    <%= link_to r, reports_disease_chart_path(:place_id => row[0], :start_date => @from_date, :end_date => @to_date, :locale => params[:locale]) %>
                  <% else %>
                    <%= r %>
                  <% end -%>
                <% else %>
                  <%= r %>
                <% end -%>
              <% elsif index > 1 %>
                <%= r %>
              <% end -%>
            </td> 
          <% end -%>
        <% end -%>         
         
      </tr>
    <% end -%>      
  </tbody>
</table>
</div>
<%# end %>

app/views/reports/disease_chart.html.erb
<div class="row-fluid">
	<%=  link_to t('action.back'), reports_path %>
	<br>
	<br>
  <div class="panel panel-default">
    <div class="panel-heading">
      <%= t('report.disease_trend_comparison_by_hc')%>      
    </div>
    <div class="panel-body">
    	<div class="row-fluid">
    		<div class="span4">
				<%= form_tag reports_create_hc_chart_path, :method => :get do %>
					<!-- <div class="text-error"></div>
					<br> -->
					<label>&nbsp;</label>
					<%= select_tag(:diseases,  options_for_select(@diseases),:multiple => true, :prompt => t('select_diseases')) %>
					<ul>
						<% @places.each do |od| %>
							<li class="od" data-id="<%= od.id %>">
								<input type="checkbox" class="parent_places" name="parent_places" id="<%= od.id %>"  value="<%= od.id %>" data-id="<%= od.id %>">
								<a href="#"><%= od.name %></a>
							</li>
							<ul class="hc" id="sub<%= od.id %>">
							<% od.children.each do |hc| %>								
								<li>
									<input type="checkbox" class="disease_places" name="<%= od.id %>"  value="<%= hc.id %>">
									<%= hc.name %>
								</li>								
							<% end -%>
							</ul>
						<% end -%>					  	
					</ul>	
					

					<label><%= t('from')%><span class="text-error">*</span></label>
					<div class="input-append">
					  <input class="span6" id="start_date" type="text" name="start_date" value="<%= params[:start_date] %>" >
					  <button class="btn" type="button" id="btn_start_date"><i class="icon-calendar"></i></button>
					</div>
					<p id="start_date_error_msg" class="text-error"></p>

					
					<label><%= t('to')%><span class="text-error">*</span></label>
					<div class="input-append">
					  <input class="span6" id="end_date" type="text" name="end_date" value="<%= params[:end_date] %>" >
					  <button class="btn" type="button" id="btn_end_date"><i class="icon-calendar"></i></button>
					</div>	
					<p id="end_date_error_msg" class="text-error"></p>

					<input type="hidden" value="<%= params[:place_id] %>" id="place_id">
					<br>
					<div class="span2 offset3">
						<input type="button" value="<%= t('action.submit')%>" name="submit" class="btn btn-primary" id="btn_create_col_chart">
					</div>


				<% end -%>
    		</div>
    		<div class="span8">
    			<div id="disease_chart" style="width:100%; height:100%"></div>
    		</div>
    	</div>
    </div>
  </div>
</div>




<script type="text/javascript">
	google.load('visualization', '1.0', {'packages':['corechart']});
	
	$(document).ready(function(){	

	
		$("#start_date").datepicker({
			format:'yyyy-mm-dd'
		});	
		
		$("#end_date").datepicker({format:'yyyy-mm-dd'});	
		// $("#end_date").datepicker();	

		$("#btn_start_date").on("click", function(){
			$("#start_date").datepicker('show');

		});

		$("#btn_end_date").on("click", function(){
			$("#end_date").datepicker('show');
		});

		$("#btn_create_col_chart").on("click", function(){			
			disease_chart_request();
		});
		tmp = $("#place_id").val();
		checked_sub(tmp, true);

		$('select#diseases').find('option').each(function() {
    		 $(this).attr('selected', true);
    	});

		$('.od').on("click", function(){
			id = $(this).attr('data-id');
			checked_sub(id);
		});


    	disease_chart_request();
	});

	function checked_sub(parent_list, parent_state){
		// alert(parent_list);
		$('#sub'+parent_list).slideDown();
		if ($('#'+parent_list).is(':checked') || parent_state == true){
			$('#'+parent_list).prop('checked', true);
			$('[name='+parent_list+']').prop('checked', true);
		}else{
			$('[name='+parent_list+']').prop('checked', false);
		}
	}

	function disease_chart_request(){

		diseases = $("#diseases").val();

		places = new Array();
		$(".disease_places:checked").each(function() {
	        places.push($(this).val());
	    });

		start_date = $("#start_date").val();
		end_date = $("#end_date").val();
		if(start_date == ''){
			$("#start_date_error_msg").html(t("required_field"));
			if(end_date == ''){
				$("#end_date_error_msg").html(t("required_field"));
			}		
			return	;
		}

		if(end_date == ''){
			$("#end_date_error_msg").html(t("required_field"));
			return;
		}
		
		$("#start_date_error_msg").empty();
		$("#end_date_error_msg").empty();
		

		$.ajax('/reports/create_disease_chart', {
			type: 'GET',
			data: { places: places, start_date: start_date, end_date: end_date, diseases: diseases },
			success: function(response) { 	
				console.log(response);	
				if(response == null)
					$('p.text-error').text(t("incorrect_date_range"));
				else{		
					$('p.text-error').empty();
					drawChart(response);
				}
			},
			error: function(error) { 
		    }
		});		
	}

	function drawChart(response) {    
	  	
	    var data = new google.visualization.DataTable();
	    data.addColumn('string', 'Year');

	    arr_col = [] ;
	    index = 0;
	    b = true;
	    $.each(response, function(key,value) {
	    	for(var i in arr_col){
	    		// console.log(col);
	    		if(value['name'] == arr_col[i]){
	    			b = false;
	    			break;
	    		}else{        			
	    			b = true;
	    		}
	    	}

	    	if(b == true){
	    		
	    		arr_col[index] = value['name'];
	    		data.addColumn('number', value['name']);
	    		index++;
	    	}
	    	
	    });
	    console.log(data.getNumberOfColumns());
	   

	    tmp = [];
	    arr_row = [[]];
	    j = 0;
	    index = 1;
	    flag = false;
	    current_row = 0;
	    if (arr_col.length > 0){
	    	$.each(response, function(key,value) {
	    		d = new Date(value['created_at']);

	    		for(row=0; row< arr_row.length; row++){
	    			if(d.toString('d-MMM') == arr_row[row][0]){
	    				flag = true;
	    				current_row = row ;
	    				break;
	    			}else{
	    				flag = false;
	    			}
	    		}


	    		if(flag == false){ //not exist yet
	    			tmp[0] = d.toString('d-MMM');
	    			
	    		    for(i=0; i<data.getNumberOfColumns(); i++){
	    		    	if(value['name'] ==  data.getColumnLabel(i)){
	    		    		tmp[i] = parseInt(value['quantity']);
	    		    	}else{
	    		    		if(i > 0)
	    		    		tmp[i] = 0;
	    		    	}
	    		    }
	    		    // tmp[data.getNumberOfColumns()-1] = d.toString('d-MMM');
	    		    
	    		    arr_row[j] = tmp;
	    		    j ++;
	    		    tmp = [];

	    		}else{
	    			console.log('Equal');
	    			for(a=0; a<data.getNumberOfColumns(); a++){
	    				if(value['name'] ==  data.getColumnLabel(a)){
	    					// console.log("col "+value['name']);
	    					arr_row[current_row][a] = parseInt(value['quantity']);
	    					break;
	    				}
	    			}


	    		}
	    	});
			console.log(arr_row);
	        data.addRows(arr_row);
	        var options = {'title':'Diseases Trend Comparison by HC',
	        				'legend': {position: 'right', textStyle: {fontSize: 12}},
	                       'height':350,
	                   		vAxis: {
	        				    gridlines: {
	        				        color: 'black'						        
	        					    }
	        				}
			};

			// options.chartArea = {width: "50%", height: "70%" };
			options.chartArea = {left: 30,width: "70%"};

	        var chart = new google.visualization.ColumnChart(document.getElementById('disease_chart'));

	        chart.draw(data, options);
	    }else
	    	$('#disease_chart').html("<p class='text-info text-center'>No Data</p>");  
	}  


</script>

app/views/reports/index_ajax.html.erb
<% content_for :table do %>
<% render 'view' %>
<% end %>
<% results = { html: content_for(:table), data:@data_source, places:@places_name, time_range:@time_range} %>
<%= raw ActiveSupport::JSON.encode(results) %>