config/routes.rb
Reportwheel::Application.routes.draw do
  


  # get "tests/index"
  scope "(:locale)", locale: /en|kh/ do

    get "test/index"

    # get "ods/index"

    get "contacts/index" 
    get "places/search_place_name"
    post "contacts/create_contact"
    post "places/create_place"
    get "places/update_place"
    get "places/get_parent_level"
    get "places/get_sibling_level"

    delete "places/delete_place"
    delete "contacts/delete_contact"
    # post "users/update_phone"


    # get "reports/render_date"
    # get "reports/render_date_next_previous"
    get "reports/create_hc_chart"
    get "reports/hc_chart"
    get "reports/disease_chart"
    get "reports/create_disease_chart"
    
    resources :places do
      resources :contacts
      get 'get_children', on: :member
      
      # get 'search_place_name', on: :member
    end   

    resources :reports do
      collection do
        get :export_csv
      end
    end

    resources :users do
      get :view
      put :update_current_user
      collection do
        get :reset_password
        put :change_password          
      end
    end

  end






  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  root :to => "reports#index"

  resource :sessions
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="kh">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Zero Reporting" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <script type="text/javascript">
      window.userLanguage = "<%= user_language %>"
    </script>

  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <% if !current_user.nil? %>
          <span class="brand"><%= link_to 'Zero Reporting', reports_url %></span>
          <%# if !current_user.nil? %>
            <div class="container-fluid nav-collapse pull-right">
              <ul class="nav" >
                <li><%= link_to t('menu.report'), reports_url %></li>
                <li><%= link_to t('menu.health_structure'), places_path %></li>
                <li><%= link_to t('menu.user'), users_url %></li>

                <li class="dropdown">                    
                      <!-- <li><%#= link_to "Log in", login_path %></li> -->                 
                      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <%= t('menu.language') %>
                        <b class="caret"></b>
                      </a>
                      <ul class="dropdown-menu" id="lan_link">
                          <li><%= link_to 'English', url_for(:only_path => false, :locale => 'en') %></li>
                          <li><%= link_to 'ខ្មែរ', url_for(:only_path => false, :locale => 'kh') %></li>
                      </ul>                    
                </li>

                <li class="dropdown">                          
                      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <%= current_user.name %>
                        <b class="caret"></b>
                      </a>
                      <ul class="dropdown-menu">
                          <li><%= link_to t('menu.view_profile'), user_view_path(current_user.id) %></li>
                          <li><%= link_to t('menu.change_password'), reset_password_users_path %></li>
                          <li><%= link_to t('menu.log_out'), logout_path %></li>                      
                      </ul>                    
                </li>
                 
              </ul>
            </div> <!--/.nav-collapse -->
          <% else %>
          <span class="brand">Zero Reporting</span>
          <% end -%>

        </div>
      </div>
    </div>

<!--     <div class="container-fluid" > -->
      <div class="row-fluid">
        <div class="span1"></div>
        <div class="span10">
          <%#= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="span1">
        </div>
      </div><!--/row-->

<!--       <footer>
        <p>&copy; Company 2014</p>
      </footer> -->

   <!--  </div> --> <!-- /container -->
  </body>
</html>